### ISSUE TITLE
Teach 2 ->Bugs, Last touches -> Medium-high

### ISSUE THREAD

**Issue by MariyaPa** [raynaglieri/MILE4STEM_FSU#97] opened 2018-10-22 17:09 UTC
As we have discussed on Friday...
/720001-ad_drop   command was not working. Zhaihuan said there were 3-4 students raising hands and it was too many, so she wanted to reduce the number.
Please, double-check the message on /720001-ann_finish 
It shoud be “Lecture is finished. Ask your students if they have questions”, G 22 in design doc https://docs.google.com/spreadsheets/d/1cjmS1S_W5sPy0Kthep_rjNknZQPgfv2JZA2djjW2yrE/edit#gid=106009112

**Comment by raynaglieri** [comment] 2018-10-23 15:41
Everything already seems to be working and aligned with the design docs. For the first issue:  I will reduce the amount of students raising their hands. However, _ad_questions_ and _ad_drop_ are working as intended. What behavior were you seeing? Also for the second issue: the text already appears as requested. Were you seeing different output?

**Comment by MariyaPa** [comment] 2018-10-23 16:39
Zhaihuan said she doesn't remember what exactly it was but if you reduce the number of students raising hands - it's fine, close the issue then

**Comment by raynaglieri** [comment] 2018-10-24 04:47
I just tested again and I'm not seeing any irregularities in the commands. I'm going to close the issue for now. Will reopen if we can narrow down what was going on!

**Closed by raynaglieri** 2018-10-24 04:47 UTC
